# Configuration file for the Sphinx documentation builder.

# -- Project information

project = 'CaC FlowCharts'
copyright = '2021, Marcus Burghardt'
author = 'Marcus Burghardt'

release = '0.1'
version = '0.1.0'

# -- General configuration

extensions = ['recommonmark',
    'sphinx_rtd_theme',
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinxcontrib.autojinja.jinja',
    'sphinx.ext.autosectionlabel',
]

html_theme = 'sphinx_rtd_theme'

####

# Prefix document path to section labels, otherwise autogenerated labels would look like 'heading'
# rather than 'path/to/file:heading'
autosectionlabel_prefix_document = True

source_suffix = ['.rst', '.md']
